// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAsn1Templates")>]
[<assembly: AssemblyProductAttribute("FsAsn1Templates")>]
[<assembly: AssemblyDescriptionAttribute("F#-based Templating DSL for ASN.1 data structures")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAsn1Templates"
    let [<Literal>] AssemblyProduct = "FsAsn1Templates"
    let [<Literal>] AssemblyDescription = "F#-based Templating DSL for ASN.1 data structures"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
